#! /usr/bin/perl
use warnings;
use strict;
use Cwd qw(cwd);
use FindBin;
use File::Spec;
my $doxyfile = File::Spec->catfile($FindBin::Bin,'check-docs.conf');
my $cwd = cwd();
my @data;
if (! -f $doxyfile) {
	die "Could not find test-missing-doc-doxygen.conf config file. your PLUGIN_TEST_SUPPORT_DIR probably isn't set. This is our fault, not yours."
}


open (my $fh, "doxygen $doxyfile 2>&1 -|");

while (my $line =  <$fh>) {
	chomp($line);
	if ($line =~ /(.*) warning: (.*) is not documented./) {
	my $subline = $1. " Undocumented ". $2;
        $subline =~ s/^$cwd\///;	
	push @data, $subline;
		}
}
close($fh);


print "1..".$#data+1;
my $i = 1;
while ( my $err = shift @data) {
print "not ok ".$i++. " - ".$err."\n";
}
